"""crear modulo visitas

Revision ID: 04488e670953
Revises: bff22ad15bf9
Create Date: 2026-07-22 19:26:19.354894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04488e670953'
down_revision: Union[str, Sequence[str], None] = 'bff22ad15bf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asesor_id', sa.Integer(), nullable=False),
    sa.Column('fecha_visita', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.Column('empresa', sa.String(length=180), nullable=False),
    sa.Column('nit', sa.String(length=30), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=220), nullable=True),
    sa.Column('contacto_nombre', sa.String(length=180), nullable=True),
    sa.Column('cargo_contacto', sa.String(length=120), nullable=True),
    sa.Column('telefono_contacto', sa.String(length=30), nullable=True),
    sa.Column('email_contacto', sa.String(length=150), nullable=True),
    sa.Column('servicio', sa.String(length=120), nullable=False),
    sa.Column('tipo_visita', sa.String(length=30), nullable=False),
    sa.Column('estado', sa.String(length=30), server_default='PROGRAMADA', nullable=False),
    sa.Column('origen_registro', sa.String(length=20), server_default='WEB', nullable=False),
    sa.Column('cantidad_participantes', sa.Integer(), nullable=True),
    sa.Column('duracion_minutos', sa.Integer(), nullable=True),
    sa.Column('objetivo', sa.Text(), nullable=True),
    sa.Column('desarrollo', sa.Text(), nullable=True),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.Column('compromisos', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('nivel_satisfaccion', sa.String(length=20), nullable=True),
    sa.Column('proxima_visita', sa.Date(), nullable=True),
    sa.Column('latitud', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('firma_cliente_url', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("\n            estado IN (\n                'PROGRAMADA',\n                'EN_PROCESO',\n                'FINALIZADA',\n                'CANCELADA'\n            )\n            ", name='ck_visitas_estado'),
    sa.CheckConstraint("\n            nivel_satisfaccion IS NULL\n            OR nivel_satisfaccion IN (\n                'EXCELENTE',\n                'BUENO',\n                'REGULAR',\n                'MALO'\n            )\n            ", name='ck_visitas_nivel_satisfaccion'),
    sa.CheckConstraint("\n            origen_registro IN (\n                'WEB',\n                'MOVIL',\n                'API'\n            )\n            ", name='ck_visitas_origen_registro'),
    sa.CheckConstraint("\n            tipo_visita IN (\n                'CAPACITACION',\n                'RECAPACITACION',\n                'IMPLEMENTACION',\n                'SOPORTE',\n                'SEGUIMIENTO',\n                'COMERCIAL',\n                'LEVANTAMIENTO',\n                'OTRA'\n            )\n            ", name='ck_visitas_tipo_visita'),
    sa.CheckConstraint('\n            cantidad_participantes IS NULL\n            OR cantidad_participantes >= 0\n            ', name='ck_visitas_cantidad_participantes'),
    sa.CheckConstraint('\n            duracion_minutos IS NULL\n            OR duracion_minutos >= 0\n            ', name='ck_visitas_duracion_minutos'),
    sa.CheckConstraint('\n            hora_fin IS NULL\n            OR hora_inicio IS NULL\n            OR hora_fin >= hora_inicio\n            ', name='ck_visitas_rango_horas'),
    sa.CheckConstraint('latitud IS NULL OR latitud BETWEEN -90 AND 90', name='ck_visitas_latitud'),
    sa.CheckConstraint('longitud IS NULL OR longitud BETWEEN -180 AND 180', name='ck_visitas_longitud'),
    sa.ForeignKeyConstraint(['asesor_id'], ['asesores.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitas_asesor_id'), 'visitas', ['asesor_id'], unique=False)
    op.create_index(op.f('ix_visitas_created_by'), 'visitas', ['created_by'], unique=False)
    op.create_index(op.f('ix_visitas_empresa'), 'visitas', ['empresa'], unique=False)
    op.create_index(op.f('ix_visitas_estado'), 'visitas', ['estado'], unique=False)
    op.create_index(op.f('ix_visitas_fecha_visita'), 'visitas', ['fecha_visita'], unique=False)
    op.create_index(op.f('ix_visitas_nit'), 'visitas', ['nit'], unique=False)
    op.create_index(op.f('ix_visitas_nivel_satisfaccion'), 'visitas', ['nivel_satisfaccion'], unique=False)
    op.create_index(op.f('ix_visitas_servicio'), 'visitas', ['servicio'], unique=False)
    op.create_index(op.f('ix_visitas_tipo_visita'), 'visitas', ['tipo_visita'], unique=False)
    op.create_index(op.f('ix_visitas_updated_by'), 'visitas', ['updated_by'], unique=False)
    op.create_table('visita_evidencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visita_id', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('url_archivo', sa.Text(), nullable=False),
    sa.Column('tipo_archivo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("\n            tipo_archivo IN (\n                'FOTO',\n                'PDF',\n                'VIDEO',\n                'AUDIO',\n                'OTRO'\n            )\n            ", name='ck_visita_evidencia_tipo'),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['visita_id'], ['visitas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visita_evidencias_created_by'), 'visita_evidencias', ['created_by'], unique=False)
    op.create_index(op.f('ix_visita_evidencias_updated_by'), 'visita_evidencias', ['updated_by'], unique=False)
    op.create_index(op.f('ix_visita_evidencias_visita_id'), 'visita_evidencias', ['visita_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visita_evidencias_visita_id'), table_name='visita_evidencias')
    op.drop_index(op.f('ix_visita_evidencias_updated_by'), table_name='visita_evidencias')
    op.drop_index(op.f('ix_visita_evidencias_created_by'), table_name='visita_evidencias')
    op.drop_table('visita_evidencias')
    op.drop_index(op.f('ix_visitas_updated_by'), table_name='visitas')
    op.drop_index(op.f('ix_visitas_tipo_visita'), table_name='visitas')
    op.drop_index(op.f('ix_visitas_servicio'), table_name='visitas')
    op.drop_index(op.f('ix_visitas_nivel_satisfaccion'), table_name='visitas')
    op.drop_index(op.f('ix_visitas_nit'), table_name='visitas')
    op.drop_index(op.f('ix_visitas_fecha_visita'), table_name='visitas')
    op.drop_index(op.f('ix_visitas_estado'), table_name='visitas')
    op.drop_index(op.f('ix_visitas_empresa'), table_name='visitas')
    op.drop_index(op.f('ix_visitas_created_by'), table_name='visitas')
    op.drop_index(op.f('ix_visitas_asesor_id'), table_name='visitas')
    op.drop_table('visitas')
    # ### end Alembic commands ###
