"""agregar geolocalizacion a terceros

Revision ID: 6d1a74ca1de9
Revises: 4e25654439d5
Create Date: 2026-08-25 18:50:45.572649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d1a74ca1de9'
down_revision: Union[str, Sequence[str], None] = '4e25654439d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eventos_automatizacion_entidad'), table_name='eventos_automatizacion')
    op.drop_index(op.f('ix_eventos_automatizacion_estado_programada'), table_name='eventos_automatizacion')
    op.drop_index(op.f('ix_eventos_automatizacion_n8n_execution'), table_name='eventos_automatizacion')
    op.drop_index(op.f('ix_eventos_automatizacion_tipo_evento'), table_name='eventos_automatizacion')
    op.drop_index(op.f('ix_eventos_automatizacion_visita'), table_name='eventos_automatizacion')
    op.drop_index(op.f('uq_eventos_automatizacion_idempotencia'), table_name='eventos_automatizacion', postgresql_where='(clave_idempotencia IS NOT NULL)')
    op.drop_table('eventos_automatizacion')
    op.drop_index(op.f('ix_analisis_ia_ejecutivo_created_at'), table_name='analisis_ia_ejecutivo')
    op.drop_index(op.f('ix_analisis_ia_ejecutivo_informe'), table_name='analisis_ia_ejecutivo')
    op.drop_table('analisis_ia_ejecutivo')
    op.add_column('terceros', sa.Column('latitud', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('terceros', sa.Column('longitud', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('terceros', sa.Column('fuente_ubicacion', sa.String(length=20), server_default='SIN_VALIDAR', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terceros', 'fuente_ubicacion')
    op.drop_column('terceros', 'longitud')
    op.drop_column('terceros', 'latitud')
    op.create_table('analisis_ia_ejecutivo',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('evento_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('informe_evento_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('modelo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('openai_response_id', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('resumen_ejecutivo', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('hallazgos_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('riesgos_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('recomendaciones_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('mensaje_cierre', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uso_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('contexto_anonimizado_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.CheckConstraint("jsonb_typeof(hallazgos_json) = 'array'::text", name=op.f('ck_analisis_ia_hallazgos_array')),
    sa.CheckConstraint("jsonb_typeof(recomendaciones_json) = 'array'::text", name=op.f('ck_analisis_ia_recomendaciones_array')),
    sa.CheckConstraint("jsonb_typeof(riesgos_json) = 'array'::text", name=op.f('ck_analisis_ia_riesgos_array')),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos_automatizacion.id'], name=op.f('fk_analisis_ia_evento'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['informe_evento_id'], ['eventos_automatizacion.id'], name=op.f('fk_analisis_ia_informe_evento'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('analisis_ia_ejecutivo_pkey')),
    sa.UniqueConstraint('evento_id', name=op.f('uq_analisis_ia_ejecutivo_evento'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_analisis_ia_ejecutivo_informe'), 'analisis_ia_ejecutivo', ['informe_evento_id'], unique=False)
    op.create_index(op.f('ix_analisis_ia_ejecutivo_created_at'), 'analisis_ia_ejecutivo', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('eventos_automatizacion',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tipo_evento', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('entidad', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entidad_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('visita_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=30), server_default=sa.text("'PENDIENTE'::character varying"), autoincrement=False, nullable=False),
    sa.Column('prioridad', sa.SMALLINT(), server_default=sa.text('5'), autoincrement=False, nullable=False),
    sa.Column('intentos', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('max_intentos', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=False),
    sa.Column('fecha_programada', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('iniciado_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('procesado_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('proximo_intento_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('canal', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('destinatario', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('asunto', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('respuesta_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ultimo_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('n8n_workflow_id', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('n8n_execution_id', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('clave_idempotencia', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.CheckConstraint("estado::text = ANY (ARRAY['PENDIENTE'::character varying, 'EN_PROCESO'::character varying, 'PROCESADO'::character varying, 'ERROR'::character varying, 'REINTENTO'::character varying, 'CANCELADO'::character varying]::text[])", name=op.f('ck_eventos_automatizacion_estado')),
    sa.CheckConstraint('intentos >= 0 AND max_intentos >= 1', name=op.f('ck_eventos_automatizacion_intentos')),
    sa.CheckConstraint('prioridad >= 1 AND prioridad <= 10', name=op.f('ck_eventos_automatizacion_prioridad')),
    sa.ForeignKeyConstraint(['visita_id'], ['visitas.id'], name=op.f('fk_eventos_automatizacion_visita'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('eventos_automatizacion_pkey'))
    )
    op.create_index(op.f('uq_eventos_automatizacion_idempotencia'), 'eventos_automatizacion', ['clave_idempotencia'], unique=True, postgresql_where='(clave_idempotencia IS NOT NULL)')
    op.create_index(op.f('ix_eventos_automatizacion_visita'), 'eventos_automatizacion', ['visita_id'], unique=False)
    op.create_index(op.f('ix_eventos_automatizacion_tipo_evento'), 'eventos_automatizacion', ['tipo_evento'], unique=False)
    op.create_index(op.f('ix_eventos_automatizacion_n8n_execution'), 'eventos_automatizacion', ['n8n_execution_id'], unique=False)
    op.create_index(op.f('ix_eventos_automatizacion_estado_programada'), 'eventos_automatizacion', ['estado', 'fecha_programada'], unique=False)
    op.create_index(op.f('ix_eventos_automatizacion_entidad'), 'eventos_automatizacion', ['entidad', 'entidad_id'], unique=False)
    # ### end Alembic commands ###

def upgrade() -> None:
       op.add_column(
           "terceros",
           sa.Column("latitud", sa.Numeric(10, 7), nullable=True),
       )
       op.add_column(
           "terceros",
           sa.Column("longitud", sa.Numeric(10, 7), nullable=True),
       )
       op.add_column(
           "terceros",
           sa.Column(
               "fuente_ubicacion",
               sa.String(length=20),
               nullable=False,
               server_default="SIN_VALIDAR",
           ),
       )

def downgrade() -> None:
   op.drop_column("terceros", "fuente_ubicacion")
   op.drop_column("terceros", "longitud")
   op.drop_column("terceros", "latitud")