"""crear tabla terceros

Revision ID: 75593ab48e54
Revises: 04488e670953
Create Date: 2026-07-24 00:24:32.486960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75593ab48e54'
down_revision: Union[str, Sequence[str], None] = '04488e670953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terceros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_tercero', sa.String(length=30), nullable=False),
    sa.Column('tipo_identificacion', sa.String(length=20), nullable=False),
    sa.Column('identificacion', sa.String(length=30), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('direccion', sa.String(length=250), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('contacto_nombre', sa.String(length=150), nullable=True),
    sa.Column('contacto_email', sa.String(length=150), nullable=True),
    sa.Column('contacto_telefono', sa.String(length=30), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terceros_id'), 'terceros', ['id'], unique=False)
    op.create_index(op.f('ix_terceros_identificacion'), 'terceros', ['identificacion'], unique=True)
    op.create_index(op.f('ix_terceros_razon_social'), 'terceros', ['razon_social'], unique=False)
    op.create_index(op.f('ix_terceros_tipo_tercero'), 'terceros', ['tipo_tercero'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_terceros_tipo_tercero'), table_name='terceros')
    op.drop_index(op.f('ix_terceros_razon_social'), table_name='terceros')
    op.drop_index(op.f('ix_terceros_identificacion'), table_name='terceros')
    op.drop_index(op.f('ix_terceros_id'), table_name='terceros')
    op.drop_table('terceros')
    # ### end Alembic commands ###
