"""relacionar visitas con terceros

Revision ID: a17844fe1898
Revises: 75593ab48e54
Create Date: 2026-07-24 15:37:04.253262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a17844fe1898'
down_revision: Union[str, Sequence[str], None] = '75593ab48e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitas', sa.Column('tercero_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_visitas_tercero_id'), 'visitas', ['tercero_id'], unique=False)
    op.create_foreign_key(None, 'visitas', 'terceros', ['tercero_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visitas', type_='foreignkey')
    op.drop_index(op.f('ix_visitas_tercero_id'), table_name='visitas')
    op.drop_column('visitas', 'tercero_id')
    # ### end Alembic commands ###
