"""crear tablas iniciales asesores y usuarios

Revision ID: bff22ad15bf9
Revises: 
Create Date: 2026-07-16 23:09:06.182782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bff22ad15bf9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asesores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identificacion', sa.String(length=30), nullable=False),
    sa.Column('primer_nombre', sa.String(length=80), nullable=False),
    sa.Column('segundo_nombre', sa.String(length=80), nullable=True),
    sa.Column('primer_apellido', sa.String(length=80), nullable=False),
    sa.Column('segundo_apellido', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_asesores_email'),
    sa.UniqueConstraint('identificacion', name='uq_asesores_identificacion')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asesor_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=50), server_default='ASESOR', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("rol IN ('ADMINISTRADOR', 'COORDINADOR', 'ASESOR')", name='ck_usuarios_rol'),
    sa.ForeignKeyConstraint(['asesor_id'], ['asesores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asesor_id', name='uq_usuarios_asesor')
    )
    op.create_index(op.f('ix_usuarios_asesor_id'), 'usuarios', ['asesor_id'], unique=False)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_asesor_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('asesores')
    # ### end Alembic commands ###
